# Generated by Django 3.1.7 on 2021-03-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_order_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameExemplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена/Залог')),
                ('number_players', models.CharField(max_length=255, verbose_name='Количество игроков')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Соимость аренды')),
                ('game_time', models.CharField(max_length=255, verbose_name='Время пратии')),
                ('status', models.CharField(choices=[('available', 'Игра свободна'), ('rented', 'Игра арендована'), ('booked', 'Игра забронирована'), ('on review', 'Игра на проверке'), ('bought', 'Игра куплена'), ('spoilt', 'Игра испорчена')], default='available', max_length=100, verbose_name='Статус экземпляра')),
                ('game_category', models.ManyToManyField(blank=True, related_name='related_game', to='mainapp.GameCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='DesktopGame',
        ),
    ]
