# Generated by Django 3.1.7 on 2021-03-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210318_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameexemplar',
            name='game_category',
            field=models.ManyToManyField(blank=True, related_name='related_game_category', to='mainapp.GameCategory'),
        ),
    ]
