# Generated by Django 3.1.7 on 2021-03-19 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210319_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_boxes',
            field=models.ManyToManyField(blank=True, related_name='related_game_box', to='mainapp.GameBox', verbose_name='ID Коробок'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_category',
            field=models.ManyToManyField(related_name='related_game_category', to='mainapp.GameCategory'),
        ),
        migrations.AlterField(
            model_name='gamebox',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.game', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='gamebox',
            name='status',
            field=models.CharField(blank=True, choices=[('on storage', 'Игра на складе'), ('available', 'Игра свободна'), ('rented', 'Игра арендована'), ('booked', 'Игра забронирована'), ('on review', 'Игра на проверке'), ('bought', 'Игра куплена'), ('spoilt', 'Игра испорчена'), ('donor', 'Игра донор')], default='on storage', max_length=100, verbose_name='Статус экземпляра'),
        ),
    ]
